services:
  ros2:
    container_name: camera_ros
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     ROS_DISTRO: ${ROS_DISTRO:-jazzy}
    image: dnldnwls1123/ros:${ROS_DISTRO:-jazzy}-camera-ros
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    ipc: host
    pid: host
    environment:
     - DISPLAY=${DISPLAY}
     - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /run/udev:/run/udev
    privileged: true
    command: bash